Animals table
joyapisi/vet-clinic-db pull request #1
Opened 2023-06-05 22:12 UTC by joyapisi

# What I did:
- Create  animals table
-  Insert data to animals table
- Query animals table:
  - [Find all animals whose names ends in "mon"](https://drive.google.com/file/d/1Li7KtSDY52jJoS_AJko3WiXIxAbX9o_m/view?usp=sharing)
  - [List the name of all animals born between 2016 and 2019.](https://drive.google.com/file/d/1m_0N6GeqrmAePUhzoG2PGLQVneJsJ8MT/view?usp=drive_link)
  - [List the name of all animals that are neutered and have less than 3 escape attempts](https://drive.google.com/file/d/1MPmHmAkZ9AEzFXU-ydVlmhhe7W5eLQcW/view?usp=drive_link).
  - [List the date of birth of all animals named either "Agumon" or "Pikachu".](https://drive.google.com/file/d/1UpJSRRlQIAKF9bbPr9sCul1KjQ585df4/view?usp=drive_link)
  - [List name and escape attempts of animals that weigh more than 10.5kg](https://drive.google.com/file/d/1NjhzhYr3fGFC88nY3Dz2_r_aZ8VwN3b7/view?usp=drive_link)
  - [Find all animals that are neutered.](https://drive.google.com/file/d/1exGG3mqTKGcnMZTKfv8EdvwNphfh579S/view?usp=drive_link)
  - [Find all animals not named Gabumon.](https://drive.google.com/file/d/1zBNtJAhL4h-phPF6vfUxv-k6eJp2UsCa/view?usp=drive_link)
  - [Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)](https://drive.google.com/file/d/1Yu8_kxwUVCy0NU4X3PdiV96DWpK_qL7n/view?usp=drive_link)

2023-06-05 23:10 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @joyapisi , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark: SQL commands put in the correct files
:heavy_check_mark:  Good commit messages
:heavy_check_mark: All queries added and given required results

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] The requirements said you should take screenshots and put in the PR description and not providing links to the images. Just as I have added a screenshot below is exactly what you were expected to do. I have not just provided a link to the image.
![image](https://github.com/joyapisi/vet-clinic-db/assets/62849872/147b946e-a7bd-4a73-85ae-af53c76ff355)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 23:10 UTC, t-yanick commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] Great job working on this milestone. When I click on the MIT license link, I am re-directed to an error 404 page. Kindly fix this issue as it is not professional to allow broken links in our README.
![image](https://github.com/joyapisi/vet-clinic-db/assets/62849872/f602f1ba-0bf2-4ab2-9d52-e252c60d3c36)

2023-06-05 23:10 UTC, t-yanick commented on schema.sql
> +    name text NOT NULL,
- [ ] Kindly use `VARCHAR` for the name column and specify a length. example` name varchar(255)`.
`VARCHAR` is best suited for storing short to medium-length `strings`, while `TEXT` is better suited for storing large amounts of textual data. As you can clearly see from the project requirements, the data type recommended for name column is string.
![image](https://github.com/joyapisi/vet-clinic-db/assets/62849872/c96d5aed-cea1-4b36-a0bf-f9570c99b389)

2023-06-06 09:10 UTC, gemmen29 approved these changes
Hi @joyapisi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 09:30 UTC, merged