add multiple tables, and use primary and foreign key to query
joyapisi/vet-clinic-db pull request #3
Opened 2023-06-07 22:41 UTC by joyapisi

##  What I Did:
- Create a table named owners and populate it with data 
![1A](https://github.com/joyapisi/vet-clinic-db/assets/38925103/727b0fb3-39b1-436a-8978-536dc380364e)

- Create a table named species and populate it with data
![1B](https://github.com/joyapisi/vet-clinic-db/assets/38925103/21d0471e-e0b4-4fe6-a715-efcc1eb42efa)

- Modify animals table:
  - Make sure that id is set as autoincremented PRIMARY KEY
  - Remove column species
  - Add column species_id which is a foreign key referencing species table
  - Add column owner_id which is a foreign key referencing the owners table
![1C](https://github.com/joyapisi/vet-clinic-db/assets/38925103/b5e54c7e-71e6-45fd-a2b3-0cba85cc3e74)

- Insert data into the owners table:
![1D](https://github.com/joyapisi/vet-clinic-db/assets/38925103/a008d258-761e-4b8e-9437-b221bb73a45d)

- Insert data into the species table:
![1E](https://github.com/joyapisi/vet-clinic-db/assets/38925103/f1bc0a4f-662d-4b2a-bf4d-0a6a3d2b20ff)

- Modify data inserted to animals table so it includes the species_id value:
  - If the name ends in "mon" it will be Digimon
  - All other animals are Pokemon
![1F](https://github.com/joyapisi/vet-clinic-db/assets/38925103/7a44ff39-f533-4a10-acda-c25e048d9ed8)

- Modify your inserted animals to include owner information (owner_id):
![1G](https://github.com/joyapisi/vet-clinic-db/assets/38925103/61f64d39-2647-4e04-8436-58bb9ccc72df)

- Write queries (using JOIN) to answer the following questions:
  - What animals belong to Melody Pond?
  -  List of all animals that are pokemon (their type is Pokemon).
  -  List all owners and their animals, remember to include those that don't own any animal.
  - How many animals are there per species
  - List all Digimon owned by Jennifer Orwell.
  - List all animals owned by Dean Winchester that haven't tried to escape.
  - Who owns the most animals?
![1H](https://github.com/joyapisi/vet-clinic-db/assets/38925103/f2bff719-13c1-467c-8d7f-15e8a2c39acd)

2023-06-07 22:59 UTC, alexander16108 requested changes
Hi @joyapisi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/mNLh4BQKRrNQbFbuCF/giphy.gif"/>

## Highlights
✔️ Descriptive Readme file
✔️ Good PR
✔️ passing linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 22:59 UTC, alexander16108 commented on queries.sql
> +WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts = 0;
please as requested add the screenshot of the following queries to your PR description

- What animals belong to Melody Pond?
- List of all animals that are pokemon (their type is Pokemon).
- List all owners and their animals, remember to include those that don't own any animal.
- How many animals are there per species
- List all Digimon owned by Jennifer Orwell.
- List all animals owned by Dean Winchester that haven't tried to escape.

2023-06-08 09:48 UTC, joyapisi commented
# CHANGES MADE: 
- Update pull request to include required query photos

2023-06-08 09:53 UTC, amejid approved these changes
Hi @joyapisi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Correct workflow :heavy_check_mark: 
- SQL organized in multiple files :heavy_check_mark: 
- Good use of JOIN :heavy_check_mark: 
- Query screenshots added to PR description :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 10:03 UTC, merged